### PR TITLE
Utilize bin/setup script to handle application setup

### PR DESCRIPTION
**Pull request by edwinthinks**
This PR updates the README to suggest using `bin/setup` to source control the configuration steps. I've found this to be useful so that we keep the steps simple and consistent.

Here is an
Captura de Pantalla 2022-08-22 a la(s) 8 32 33 p m
 output log of what it looks like. And yes I added a dog emoji:
Captura de Pantalla 2022-08-22 a la(s) 8 32 27 p m

You should now be able to get the application prepared relatively quickly assuming you have ruby, Postgres, and yarn installed.

### CODE REVIEW

**Review by freestylebit — APPROVED** [review]
This works idempotently, I like how it doesn't seem to nuke the database, though there might be opportunities to create a task to reset the environment, too (in another PR, of course).

**Comment by edwinthinks** [comment]
@freestylebit I could optionally nuke the DB too :). I've often built these to make it so its a fresh fressssh start. Do you prefer that? If so, I can add that in.

**Comment by freestylebit** [comment]
Something like that should be a separate command in case a developer wants to preserve the test data s/he has on their environment.  We could probably just run `rake db:schema:load` or `rake db:reset` to achieve this without rebuilding the other dependencies.

**Comment by edwinthinks** [comment]
@freestylebit sounds good. I think then that this PR is probably sufficient for now.

By the way, I'am not sure about the etiquette, but should I wait for you or @chriszimmerman to merge in?

**Comment by freestylebit** [comment]
For now, you can merge your PR in once you get the green checkmark and as long as no one requests changes.  I used to do this at my last job to give the author time to make any last minute adjustments if needed.

**Pull request merged**
